import type { ModelDefinition } from "../core/models";

export const qwenConfig = {
  id: "qwen",
  name: "Qwen",
  defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
  apiKeyPrompt: "Enter your Qwen API Key",
  apiKeyPlaceholder: "Qwen API Key",
  supportsThinking: true,
  models: [
    {
      id: "qwen3.7-max",
      name: "Qwen3.7 Max",
      family: "qwen",
      version: "3.7",
      detail: "Flagship reasoning agent model with 1M context window",
      maxInputTokens: 1000000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: false, thinking: true },
      requiresThinkingParam: true,
    },
    {
      id: "qwen3.7-plus",
      name: "Qwen3.7 Plus",
      family: "qwen",
      version: "3.7",
      detail: "Multimodal agent flagship with vision & language, 1M context",
      maxInputTokens: 1000000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: true, thinking: true },
      requiresThinkingParam: true,
    },
    {
      id: "qwen3.6-flash",
      name: "Qwen3.6 Flash",
      family: "qwen",
      version: "3.6",
      detail: "Fast, cost-efficient model with 1M context window",
      maxInputTokens: 1000000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: true, thinking: true },
      requiresThinkingParam: true,
    },
    {
      id: "qwen3-max",
      name: "Qwen3 Max",
      family: "qwen",
      version: "3",
      detail: "Flagship model with advanced reasoning capabilities",
      maxInputTokens: 128000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: true, thinking: true },
      requiresThinkingParam: true,
    },
    {
      id: "qwen3.6-plus",
      name: "Qwen3.6 Plus",
      family: "qwen",
      version: "3.6",
      detail: "Enhanced model with improved performance",
      maxInputTokens: 128000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: true, thinking: true },
      requiresThinkingParam: true,
    },
    {
      id: "qwen3.5-flash",
      name: "Qwen3.5 Flash",
      family: "qwen",
      version: "3.5",
      detail: "Fast inference model for quick responses",
      maxInputTokens: 128000,
      maxOutputTokens: 64000,
      capabilities: { toolCalling: true, imageInput: true, thinking: true },
      requiresThinkingParam: true,
    },
  ] satisfies ModelDefinition[],
};
